CREATE TABLE MASTER.PURGE_CRITERIA_DETAIL
( 
SCHEMA_NAME VARCHAR NOT NULL,
TABLE_NAME VARCHAR,
COLUMN_NAME VARCHAR,
OPERATOR VARCHAR,
OPERATOR_VALUE VARCHAR,
CREATED_USER VARCHAR,
CREATED_TS VARCHAR,
UPDATED_USER VARCHAR,
UPDATED_TS VARCHAR,
CONSTRAINT PURGE_CRITERIA_DETAIL_PK  PRIMARY KEY (SCHEMA_NAME,TABLE_NAME,COLUMN_NAME))  default_column_family='cf',column_encoded_bytes=0;